### ISSUE TITLE
Formal issue, for indentation.

### ISSUE THREAD

**Issue by tejastank** [btwael/mammouth#48] opened 2015-01-13 11:38 UTC
{{

class tejastank_snippetbucket
    t = 1
    b = 3
  

}}

not converting with right indentation as in mammouth script -> php script

**Comment by btwael** [comment] 2015-01-13 14:42
Did you mean that output code are not well formated?

**Comment by tejastank** [comment] 2015-01-13 21:01
Yes, output code not formatted in php.

**Comment by btwael** [comment] 2015-01-14 00:50
close this as duplicate of #40

**Closed by btwael** 2015-01-14 00:50 UTC
